// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AT01UdanarejestracjauytkownikaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void aT01Udanarejestracjauytkownika() {
    driver.get("http://localhost:8080/accounts/controller?action=db_reset");
    driver.manage().window().setSize(new Dimension(945, 1012));
    assertThat(driver.findElement(By.linkText("Register")).getText(), is("Register"));
    driver.findElement(By.linkText("Register")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("Jan");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("123");
    driver.findElement(By.name("repeat_password")).click();
    driver.findElement(By.name("repeat_password")).sendKeys("123");
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Jan Nowak");
    driver.findElement(By.name("addressData")).click();
    driver.findElement(By.name("addressData")).sendKeys("Polna 13, Poznań");
    driver.findElement(By.name("submit")).click();
    assertThat(driver.findElement(By.cssSelector("h3")).getText(), is("Login"));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("Jan");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("123");
    driver.findElement(By.name("submit")).click();
    assertThat(driver.findElement(By.cssSelector("#container > div:nth-child(2)")).getText(), is("Jan Nowak, Polna 13, Poznań"));
  }
}
